In [1]:
import numpy as np

In [2]:
#create array , matrix

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1, 2],[3, 4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
#shape
print(a.shape , b.shape)

(4,) (2, 2)


In [9]:
#reshape
c = a.reshape((4, 1))
c.shape


(4, 1)

In [13]:
d = a.reshape((2, 2, -1)) #It means the array has 2 blocks, each block has 2 rows and 1 column.
d.shape

(2, 2, 1)

In [14]:
d

array([[[1],
        [2]],

       [[3],
        [4]]])