In [3]:
import numpy as np

In [4]:
#create array , matrix

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
b = np.array([[1, 2],[3, 4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
#shape
print(a.shape , b.shape)

(4,) (2, 2)


In [7]:
#reshape
c = a.reshape((4, 1))
c.shape


(4, 1)

In [8]:
d = a.reshape((2, 2, -1)) #It means the array has 2 blocks, each block has 2 rows and 1 column.
d.shape

(2, 2, 1)

In [9]:
#concatenate

a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c


array([1, 2, 3, 4, 5])

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a * b
c

array([ 4, 10, 18])

In [12]:
c = np.array([10])
d = a + c 
d

array([11, 12, 13])

In [14]:
#broadcasting 
e = a + 5
e

array([6, 7, 8])

In [17]:
#slice      list_name[start:end:step]
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [18]:
b = a[2:7:2]
b

array([3, 5, 7])

In [19]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [20]:
#math function
sum_a = np.sum(a)
sum_a

np.int64(36)

In [26]:
a = np.array([4, 2, 9, 6, 5, 1])
b = np.sort(a)
b

array([1, 2, 4, 5, 6, 9])

In [28]:

array_1 = np.arange(10)
array_2 = np.arange(1, 10).reshape(3, 3)
array_3 = np.full(5, 7)

print("dtype:", array_1.dtype)
print("sum:", array_1.sum())
print("mean:", array_1.mean())

dtype: int64
sum: 45
mean: 4.5


In [29]:

array_1 = np.arange(10)
array_2 = np.arange(1, 10).reshape(3, 3)
array_3 = np.full(5, 7)

print("dtype:", array_1.dtype)
print("sum:", array_1.sum())
print("mean:", array_1.mean())

dtype: int64
sum: 45
mean: 4.5


In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)
print(a * b)
print(a ** 2)
print(b.sum())

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
100


In [32]:
arr = np.arange(12).reshape(3, 4)
print(arr)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [33]:
rand_arr = np.random.rand(10)
print("Random:", rand_arr)
print("Mean:", rand_arr.mean())
print("Min:", rand_arr.min())
print("Max:", rand_arr.max())

mat = np.random.rand(3, 3)
print("Matrix:\n", mat)
print("Det:", np.linalg.det(mat))

Random: [0.58440784 0.89537923 0.47251631 0.59211762 0.59005703 0.98812722
 0.82103364 0.76573745 0.55673219 0.43330761]
Mean: 0.6699416140043133
Min: 0.43330760872526386
Max: 0.988127222366269
Matrix:
 [[0.5270918  0.28344619 0.55149676]
 [0.09043036 0.86925322 0.72667158]
 [0.96054504 0.83022555 0.68356218]]
Det: -0.24354968017243123
